Repository caicloud/kube-ladder, pull requests merged in 2019-07, with the labels that each got.

#2 feat(*): init commit
  OWNERS
  README.md
  tutorials/4-concepts-104.md
  tutorials/images/deployment_initial.png
  tutorials/images/deployment_scale.png
  tutorials/images/deployment_service.png
  tutorials/images/deployment_update_1.png
  tutorials/images/deployment_update_2.png
  tutorials/images/deployment_update_done.png
  tutorials/images/deployment_update_initial.png
  tutorials/images/hpa.png
  tutorials/images/kubernetes_cluster.png
  tutorials/images/labels.png
  tutorials/lab1-installation.md
  tutorials/lab2-application-and-service.md
  tutorials/lab3-manual-installtion.md
  tutorials/resources/claas.yaml
  tutorials/resources/coredns.yaml
  tutorials/resources/daemonset.yaml
  tutorials/resources/debian.yaml
  tutorials/resources/debian_never_restart.yaml
  tutorials/resources/emptydir_pod.yaml
  tutorials/resources/game.properties
  tutorials/resources/job.yaml
  tutorials/resources/kube-flannel.yaml
  tutorials/resources/ns.yaml
  tutorials/resources/pod.yaml
  tutorials/resources/pod_configmap.yaml
  tutorials/resources/pod_exceeds_quota.yaml
  tutorials/resources/pod_health.yaml
  tutorials/resources/pod_unhealth.yaml
  tutorials/resources/pod_with_pvc.yaml
  tutorials/resources/pv_hostpath.yaml
  tutorials/resources/pvc.yaml
  tutorials/resources/pvc_standard.yaml
  tutorials/resources/quota.yaml
  tutorials/resources/ui.properties
Labels: caicloud-cla: yes, release-note-none, size/XXL

#3 docs(readme): nit fix
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#4 docs(*): rename lab4 & update link
  README.md
  tutorials/lab4-concepts.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#5 Update README.md
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#6 misc clean
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#7 Add a new stage
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#11 chore(*): update emoji & nit fix
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#14 docs(*): polish & add more effective links
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#17 fix(readme): fix a typo
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#16 docs(*): translate lab1 to Chinese
  tutorials/lab1-installation.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#19 modify README.md
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#21 docs(*): add caicloud blog
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#22 Rename claas.yaml to class.yaml
  tutorials/resources/class.yaml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#23 add scheduler framework
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
